name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check formatting
      run: project/bin/scalafmt --test
    - name: Check file headers
      run: sbt headerCheck
    - name: Run tests
      run: sbt test
